### ISSUE TITLE
ImportError: No module named 'LSP'

### ISSUE THREAD

**Issue by carlmjohnson** [sublimelsp/LSP-tailwindcss#18]
I get this error in my console:

```
reloading python 3.3 plugin LSP-tailwindcss.plugin
Traceback (most recent call last):
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text 4.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/adhoc/Library/Application Support/Sublime Text 3/Installed Packages/LSP-tailwindcss.sublime-package/plugin.py", line 5, in <module>
ImportError: No module named 'LSP'
```

But I have LSP v1.7.0 installed.

**Comment by rchl** [comment]
Have you restarted ST after installing those packages?

**Comment by carlmjohnson** [comment]
Yes.

**Comment by rchl** [comment]
Is there maybe some other error earlier in the sublime text console output?

**Comment by carlmjohnson** [comment]
Somehow LSP, though installed, was disabled. I re-enabled it and that fixed the problem.
