### ISSUE TITLE
TypeError: sequence item 8: expected str instance, NoneType found

### ISSUE THREAD

**Issue by zigi05** [sublimelsp/LSP-tailwindcss#21]
It works well in [tailwind-example](https://github.com/ParamagicDev/tailwind-example) on my local machine, however it doesn't work in my project. I noticed that tailwind-example uses tailwindcss@1.1.2, and when I update it to tailwindcss@2.2.9 as in my project, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\pcuser\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 175, in on_capability_added_async
  File "C:\Users\pcuser\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 96, in _register_auto_complete_triggers
  File "C:\Users\pcuser\AppData\Roaming\Sublime Text\Installed Packages\LSP.sublime-package\plugin/session_view.py", line 130, in _apply_auto_complete_triggers
TypeError: sequence item 8: expected str instance, NoneType found
```

**Comment by zigi05** [comment]
So how to fix it?

**Comment by predragnikolic** [comment]
I tried to filter out `None` values from trigger chars, 
but even then intellisense wont work, and it is probably due to this error:
```
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/postcss/lib/processor.js:168:15)
    at new Processor (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/postcss/lib/processor.js:52:25)
    at postcss (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/postcss/lib/postcss.js:55:10)
    at /home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/lib/util/parseObjectStyles.js:24:33
    at arrayMap (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/node_modules/lodash/lodash.js:653:23)
    at map (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/node_modules/lodash/lodash.js:9622:14)
    at Function.flatMap (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/node_modules/lodash/lodash.js:9325:26)
    at parseObjectStyles (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/lib/util/parseObjectStyles.js:23:26)
    at parseObjectStyles (/home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/lib/util/parseObjectStyles.js:20:12)
    at /home/predragnikolic/Documents/sandbox/tailwind-example/node_modules/tailwindcss/lib/util/processPlugins.js:41:123
```

**Comment by predragnikolic** [comment]
@zigi05 let me know if this fixed your problem :-)

**Comment by zigi05** [comment]
> @zigi05 let me know if this fixed your problem :-)

Following your fix, I made it work in _tailwind-example_, however, it still wasn't working in my project even though I made sure that all versions were the same. I found out that the issue was with `tailwind.config.js` in my project. Once I've placed it inside working _tailwind-example_ folder, it broke the LSP-tailwindcss there as well with the same error as in my original post.

What can be wrong with my `tailwind.config.js` that makes LSP-tailwindcss not work as it's compiled correctly otherwise.

My project `tailwind.config.js`:
```
const colors = require('tailwindcss/colors');

module.exports = {
  purge: [],
  darkMode: false,
  theme: {
    container: {
      center: true,
      padding: '1rem',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.trueGray,
      primary: '#6206BF',
      secondary: '#C5C5FA',
      accent: '#F90C0C',
    },
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```
